export const translations = {
  ar: {
    appName: 'نت كنترول', home: 'الرئيسية', network: 'الشبكة', devices: 'الأجهزة',
    openwrt: 'OpenWrt', settings: 'الإعدادات',
    status: 'حالة الاتصال', online: 'متصل', connecting: 'جارٍ الاتصال', offline: 'غير متصل',
    ipAddress: 'عنوان IP', gateway: 'البوابة', dns: 'DNS', internet: 'الإنترنت',
    ping: 'زمن الاستجابة', download: 'التنزيل', upload: 'الرفع',
    connectedDevices: 'الأجهزة المتصلة', ssid: 'اسم الشبكة', connType: 'نوع الاتصال',
    uptime: 'مدة التشغيل', cpu: 'المعالج', ram: 'الذاكرة', storage: 'التخزين',
    routerInfo: 'معلومات الراوتر', wifi: 'واي فاي', dhcp: 'DHCP', firewall: 'جدار الحماية',
    wan: 'WAN', lan: 'LAN', traffic: 'حركة البيانات', commands: 'أوامر OpenWrt',
    generator: 'مولّد الأوامر', copy: 'نسخ', copied: 'تم النسخ ✓', run: 'تنفيذ',
    refresh: 'تحديث', search: 'بحث...', deviceName: 'اسم الجهاز', mac: 'عنوان MAC',
    interface: 'الواجهة', rx: 'استقبال', tx: 'إرسال', connect: 'اتصال', disconnect: 'قطع الاتصال',
    testConn: 'اختبار الاتصال', routerIP: 'عنوان الراوتر', username: 'اسم المستخدم',
    password: 'كلمة المرور', port: 'المنفذ', protocol: 'البروتوكول',
    appearance: 'المظهر', language: 'اللغة', notifications: 'الإشعارات',
    autoRefresh: 'تحديث تلقائي', interval: 'فترة التحديث (ثانية)', cache: 'التخزين المؤقت',
    about: 'حول التطبيق', version: 'الإصدار', resetApp: 'إعادة تعيين التطبيق',
    clearCache: 'مسح الذاكرة المؤقتة', demoMode: 'الوضع التجريبي',
    nativeRequired: 'يتطلب خدمة Android أصلية',
    nativeDesc: 'هذه الوظيفة غير متاحة في المتصفح وتتطلب Android Native Bridge أو Backend: 'تم الاتصال بالراوتر ✓', disconnected: 'تم قطع الاتصال',
    invalidIP: 'عنوان IP غير صالح ✕', offlineWarn: '⚠ الراوتر غير متصل',
    netError: 'خطأ في الشبكة', authError: 'فشل المصادقة', timeoutError: 'انتهت المهلة',
    themeDark: 'داكن', themeLight: 'فاتح', themeSystem: 'النظام',
    favAdded: 'أُضيف إلى المفضلة ★', favRemoved: 'أُزيل من المفضلة',
    noDevices: 'لا توجد أجهزة متصلة', generate: 'توليد الأمر', result: 'النتيجة',
    sensitive: 'أمر حساس', installPrompt: 'ثبّت التطبيق'
  },
  en: {
    appName: 'NetControl', home: 'Home', network: 'Network', devices: 'Devices',
    openwrt: 'OpenWrt', settings: 'Settings',
    status: 'Connection Status', online: 'Online', connecting: 'Connecting', offline: 'Offline',
    ipAddress: 'IP Address', gateway: 'Gateway', dns: 'DNS', internet: 'Internet',
    ping: 'Ping', download: 'Download', upload: 'Upload',
    connectedDevices: 'Connected Devices', ssid: 'SSID', connType: 'Connection Type',
    uptime: 'Uptime', cpu: 'CPU', ram: 'RAM', storage: 'Storage',
    routerInfo: 'Router Information', wifi: 'Wi-Fi', dhcp: 'DHCP', firewall: 'Firewall',
    wan: 'WAN', lan: 'LAN', traffic: 'Traffic', commands: 'OpenWrt Commands',
    generator: 'Command Generator', copy: 'Copy', copied: 'Copied ✓', run: 'Run',
    refresh: 'Refresh', search: 'Search...', deviceName: 'Device Name', mac: 'MAC Address',
    interface: 'Interface', rx: 'RX', tx: 'TX', connect: 'Connect', disconnect: 'Disconnect',
    testConn: 'Test Connection', routerIP: 'Router IP', username: 'Username',
   

> ⚠️ The response reached the length limit. Reply **continue** to get the rest.
